name: Pull request to main

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: PR build and CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm clean-install

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test

